spring.application.name=demo-integration-api

# properties configura o path base para a url dos endpoints
# exemplo de url http://localhost:8080/api/
server.servlet.context-path=/api

# Definicao app consumer default
default.app.key=${APP_CONSUMER_KEY:secret-key}
default.app.owner=${APP_CONSUMER_OWNER:clienteTeste}
default.app.limit=${APP_CONSUMER_LIMIT:100}
